---
title: "inequality vs social spending"
author: "Tivas Gupta"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
library(janitor)
library(tidyverse)
library(readxl)
```

```{r, warning = FALSE, message = FALSE}

#This is a code chunk for the other set of data, let me read it in first.


#view(new_populist)

inequality <- read_csv("Income Inequality Data by Country.csv")


tidy_inequality <- inequality %>%
  pivot_longer(cols = -Year, 
               names_to = "Country Name", 
               values_to = "Inequality Data") 

location <- tidy_inequality %>%
  mutate(`Country Name` = `Country Name` %>%
                          substring(21)) %>%
  mutate(`Country Name` = gsub( "_.*$", "_", `Country Name`)) %>%
  mutate(`Country Name` = substr(`Country Name`, 
                                 1, 
                                 nchar(`Country Name`)-1)) %>%
  mutate(`Country Name` = paste(toupper(substring(`Country Name`, 1,1)),
                                (substring(`Country Name`, 2,nchar(`Country Name`))),
                                 sep="")) %>%
  rename(country = `Country Name`) %>%
  rename(year = Year)

inequality <- location %>%
  filter(!is.na(`Inequality Data`))

named_inequality <- inequality %>%
  mutate(`Country name` = (substr(country, 1, nchar(`country`) - 40))) #%>%
  #mutate(`Nation` = ifelse(`Country name` == "New", 
                           #"New Zealand", 
                           #(substr(`Country name`, 1, nchar(`Country name`) - 8)))) 
#view(named_inequality)

final_inequality <- named_inequality %>%
  select(year, `Country name`, `Inequality Data`) %>%
  rename(country2 = `Country name`) %>%
  mutate(country = ifelse(country2 == "USA", "United States", 
                          (ifelse(country2 == "Russian Federation", "Russia", country2)))) %>% 
  select(-country2) 

#The Social spending data uses three letter country abbrevations, or codes, so I had to make a dataset with all of those codes and countries. Otherwise it would have been way to difficult to join the social spending data with the inequality data.

codes <- read_excel("codes.xlsx")

#final_inequality

#I have both the Social Spending and Social Spending as a percentage of GDP for
#this data. Not sure which one will work better, but I am guessing by GDP
#because then it will ideally scale for all countries.

#I started with SOcial Spending by accident but hopefully I can just switch to
#by percentage of GDP easily without chanigng other code.

spending <- read_csv("Social Spending OECD Percentage.csv")

#View(spending)

#View(codes)

spending <- spending %>%
  filter(SUBJECT == "PUB")

spending <- left_join(spending, codes, by = "LOCATION") %>% 
  select(Country, TIME, Value) %>%
  mutate(Social_GDP = Value) %>%
  select(-Value)

#spending 

#final_inequality

final_inequality2 <- final_inequality %>%
  mutate(TIME = year,
         Country = country) %>%
  select(-year, -country)

#final_inequality2

joined_social_ineq <- left_join(spending, 
                                final_inequality2,
                                by = c("TIME", "Country"))
joined_social_ineq

ggplot(joined_social_ineq, aes(x = Social_GDP,
                               y = `Inequality Data`)) + geom_point() + geom_smooth(method = lm, se = FALSE) + labs(title = "Inequality vs Populist Levels of Leaders", 
                                                                                                 subtitle =  "Social Spending Data is from the OECD") + ylab("Inequality Score") + xlab("Social Spending as a Percentage of GDP") + theme_classic()
#+ #geom_smooth(se = FALSE, method = "linear")
#lm()
model_1 <- lm(data = joined_social_ineq, 
               `Inequality Data` ~  Social_GDP)

#model_1

#model_1 %>%
#  tidy(conf.int = TRUE)

#joined_social_ineq %>%
#  filter(Social_GDP == 0)

#joined_social_ineq %>%
#  arrange(desc(Social_GDP))

#This is a very nice Graph that I will make prettier and include in my final
#project.
#ggsave("social_spending.png")
```

```{r}

#Now we want to undergo a similar process, but this time with happiness by
#countries instead of social spending.

happiness_metrics <- read_excel("Happiness Dataset.xls") %>%
  select(`Country name`, Year, )

#So these are just the metrics they used to determine the happiness score; could
#be helpful, but I am probably just going to use the happiness score. That is
#just from 2019 though which is a little unfortanate.
#View(Happiness_Dataset)

inequality_2019 <- final_inequality %>%
  filter(year == 2019)

#There is no 2019 data, so we will just use data from when it is most recently
#availible, which is 2015. We will also use the happiness scores from that year.

#final_inequality %>% arrange(desc(year))

inequality_2015 <- final_inequality %>%
  filter(year == 2015) %>%
  mutate(Country = country) %>%
  select(-country)

happiness_2015 <- read_csv("2015.csv")

#View(inequality_2015)

inequality_happiness_2015 <- left_join(happiness_2015,
                                       inequality_2015, 
                                       by = "Country")

#inequality_happiness_2015 
inequality_happiness_2015$ID <- seq.int(nrow(inequality_happiness_2015))
ggplot(inequality_happiness_2015 %>% mutate(time=158), 
       aes(x = `Inequality Data`, 
           y = `Happiness Score`, 
           color = Region)) + geom_point() #+
  #enter_fade()

#Hmmm looks pretty good, we will construct a model now.

model_2 <- lm(`Happiness Score` ~ `Inequality Data`, 
              data = inequality_happiness_2015)

#model_2 %>%
  #tidy(conf.int = TRUE)

ggsave("happiness.png")
```

